"""empty message

Revision ID: 107b73a25ef6
Revises: 4228171c17db
Create Date: 2015-06-09 21:46:13.738306

"""

# revision identifiers, used by Alembic.
revision = '107b73a25ef6'
down_revision = '4228171c17db'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
