"""empty message

Revision ID: 293d43baa00c
Revises: 107b73a25ef6
Create Date: 2015-06-09 21:56:14.771505

"""

# revision identifiers, used by Alembic.
revision = '293d43baa00c'
down_revision = '107b73a25ef6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'posts_author_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'author_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'posts_author_id_fkey', 'posts', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###
