"""empty message

Revision ID: 3c9d8d8ebec8
Revises: 293d43baa00c
Create Date: 2015-06-09 21:58:30.845901

"""

# revision identifiers, used by Alembic.
revision = '3c9d8d8ebec8'
down_revision = '293d43baa00c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'author_id')
    ### end Alembic commands ###
